jobs:
- job: Build
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: |
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES="armv7;armv7s"
      cmake --build .
