jobs:
- job: Build
  pool: 'macOS-10.14'
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_DEPLOYMENT_TARGET=7.0 -DCMAKE_OSX_ARCHITECTURES="armv7;armv7s"
      cmake --build .
